-- ============================================
-- EXERCICE: Trigger BEFORE INSERT (validation)
-- NIVEAU: 🔴 Avancé - Triggers
-- CONCEPTS: BEFORE INSERT, validation, RAISE EXCEPTION
--
-- 📚 Documentation PostgreSQL :
-- - [CREATE TRIGGER](https://www.postgresql.org/docs/current/sql-createtrigger.html)
-- - [Trigger Functions](https://www.postgresql.org/docs/current/plpgsql-trigger.html)
-- - [RAISE](https://www.postgresql.org/docs/current/plpgsql-errors-and-messages.html)
--
-- 🎯 OBJECTIF PÉDAGOGIQUE:
-- Créer un trigger qui valide les données AVANT insertion
-- et empêche l'insertion si les données sont invalides.
--
-- 💡 QU'EST-CE QU'UN TRIGGER ?
-- Un trigger est une procédure qui s'exécute automatiquement
-- en réponse à un événement (INSERT, UPDATE, DELETE).
--
-- Types de triggers:
-- - BEFORE : s'exécute AVANT l'opération (peut modifier/rejeter)
-- - AFTER : s'exécute APRÈS l'opération (pour audit, notifications)
--
-- ⚠️ ARCHITECTURE POSTGRESQL:
-- 1. Créer d'abord une FUNCTION qui retourne TRIGGER
-- 2. Créer ensuite le TRIGGER qui appelle cette fonction
--
-- ============================================
-- CONSIGNE:
-- Créez un trigger 'trg_validate_game_insert' qui valide les données
-- avant l'insertion d'un nouveau jeu dans la table 'games'.
--
-- Nom fonction: validate_game_insert
-- Nom trigger: trg_validate_game_insert
-- Table: games
-- Moment: BEFORE INSERT
--
-- Validations:
-- 1. Le nom du jeu (NEW.name) ne doit pas être vide
--    → Si vide, RAISE EXCEPTION 'Game name cannot be empty'
--
-- 2. L'année (NEW.year) doit être entre 1970 et l'année courante
--    → Si invalide, RAISE EXCEPTION 'Invalid game year'
--
-- 3. Si metacritic est fourni, il doit être entre 0 et 100
--    → Si invalide, RAISE EXCEPTION 'Metacritic score must be between 0 and 100'
--
-- 💡 SYNTAXE POSTGRESQL:
-- -- Étape 1: Créer la fonction trigger
-- CREATE OR REPLACE FUNCTION validate_game_insert()
-- RETURNS TRIGGER
-- LANGUAGE plpgsql
-- AS \$\$
-- BEGIN
--     -- NEW contient la nouvelle valeur à insérer
--
--     IF NEW.name IS NULL OR LENGTH(TRIM(NEW.name)) = 0 THEN
--         RAISE EXCEPTION 'Game name cannot be empty';
--     END IF;
--
--     IF NEW.year < 1970 OR NEW.year > EXTRACT(YEAR FROM CURRENT_DATE) THEN
--         RAISE EXCEPTION 'Invalid game year';
--     END IF;
--
--     IF NEW.metacritic IS NOT NULL AND (NEW.metacritic < 0 OR NEW.metacritic > 100) THEN
--         RAISE EXCEPTION 'Metacritic score must be between 0 and 100';
--     END IF;
--
--     RETURN NEW;  -- OBLIGATOIRE pour BEFORE triggers
-- END;
-- \$\$;
--
-- -- Étape 2: Créer le trigger
-- CREATE TRIGGER trg_validate_game_insert
-- BEFORE INSERT ON games
-- FOR EACH ROW
-- EXECUTE FUNCTION validate_game_insert();
--
-- 💡 UTILISATION:
-- -- Cette insertion devrait réussir
-- INSERT INTO games (name, year, metacritic) VALUES ('Valid Game', 2023, 85);
--
-- -- Cette insertion devrait échouer (nom vide)
-- INSERT INTO games (name, year, metacritic) VALUES ('', 2023, 85);
--
-- -- Cette insertion devrait échouer (année invalide)
-- INSERT INTO games (name, year, metacritic) VALUES ('Old Game', 1800, 85);
--
-- ⚠️ DIFFÉRENCES POSTGRESQL vs MariaDB:
-- 1. Fonction séparée obligatoire (RETURNS TRIGGER)
-- 2. RAISE EXCEPTION au lieu de SIGNAL SQLSTATE
-- 3. EXECUTE FUNCTION au lieu de code inline
-- 4. RETURN NEW obligatoire pour BEFORE triggers
-- 5. LENGTH(TRIM()) au lieu de = ''
-- 6. Pas de DELIMITER (utilise \$\$)
--
-- 💡 RETURN dans triggers:
-- - BEFORE INSERT/UPDATE: RETURN NEW (valider/modifier)
-- - BEFORE INSERT/UPDATE: RETURN NULL (annuler l'opération)
-- - BEFORE DELETE: RETURN OLD (valider)
-- - AFTER: RETURN NULL (valeur ignorée)
--
-- 💡 NEW vs OLD:
-- - NEW : contient les nouvelles valeurs (INSERT, UPDATE)
-- - OLD : contient les anciennes valeurs (UPDATE, DELETE)
-- ============================================

