-- ============================================
-- EXERCICE: Trigger BEFORE UPDATE (historique)
-- NIVEAU: 🔴 Avancé - Triggers
-- CONCEPTS: BEFORE UPDATE, OLD vs NEW, historique
--
-- 📚 Documentation PostgreSQL :
-- - [CREATE TRIGGER](https://www.postgresql.org/docs/current/sql-createtrigger.html)
-- - [Trigger OLD and NEW](https://www.postgresql.org/docs/current/plpgsql-trigger.html#PLPGSQL-DML-TRIGGER)
--
-- 🎯 OBJECTIF PÉDAGOGIQUE:
-- Créer un trigger qui conserve l'historique des modifications
-- en enregistrant les anciennes valeurs avant UPDATE.
--
-- 💡 OLD vs NEW dans un UPDATE:
-- - OLD : valeurs AVANT la modification
-- - NEW : valeurs APRÈS la modification
--
-- On peut comparer OLD.colonne et NEW.colonne pour détecter
-- les changements et agir en conséquence.
--
-- ============================================
-- CONSIGNE:
-- Créez une table d'historique 'games_history', puis une fonction
-- trigger et un trigger qui enregistre les modifications.
--
-- Étape 1: Créer la table games_history
-- Étape 2: Créer la fonction trigger track_game_updates
-- Étape 3: Créer le trigger trg_track_game_updates
--
-- Table: games
-- Moment: BEFORE UPDATE
--
-- Action:
-- Insérer dans games_history uniquement si le nom OU le metacritic a changé
-- avec:
-- - game_id: NEW.id
-- - old_name: OLD.name
-- - new_name: NEW.name
-- - old_metacritic: OLD.metacritic
-- - new_metacritic: NEW.metacritic
-- - changed_at: NOW()
--
-- 💡 SYNTAXE POSTGRESQL:
-- -- Étape 1: Table historique
-- CREATE TABLE IF NOT EXISTS games_history (
--     history_id SERIAL PRIMARY KEY,
--     game_id INT,
--     old_name VARCHAR(255),
--     new_name VARCHAR(255),
--     old_metacritic SMALLINT,
--     new_metacritic SMALLINT,
--     changed_at TIMESTAMP DEFAULT NOW()
-- );
-- CREATE INDEX IF NOT EXISTS idx_history_game ON games_history(game_id);
-- CREATE INDEX IF NOT EXISTS idx_history_time ON games_history(changed_at);
--
-- -- Étape 2: Fonction trigger
-- CREATE OR REPLACE FUNCTION track_game_updates()
-- RETURNS TRIGGER
-- LANGUAGE plpgsql
-- AS \$\$
-- BEGIN
--     -- Enregistrer seulement si quelque chose a changé
--     IF (OLD.name IS DISTINCT FROM NEW.name) OR
--        (OLD.metacritic IS DISTINCT FROM NEW.metacritic)
--     THEN
--         INSERT INTO games_history (
--             game_id, old_name, new_name,
--             old_metacritic, new_metacritic, changed_at
--         )
--         VALUES (
--             NEW.id, OLD.name, NEW.name,
--             OLD.metacritic, NEW.metacritic, NOW()
--         );
--     END IF;
--
--     RETURN NEW;
-- END;
-- \$\$;
--
-- -- Étape 3: Trigger
-- CREATE TRIGGER trg_track_game_updates
-- BEFORE UPDATE ON games
-- FOR EACH ROW
-- EXECUTE FUNCTION track_game_updates();
--
-- 💡 UTILISATION:
-- -- Mettre à jour un jeu
-- UPDATE games SET metacritic = 95 WHERE id = 123;
--
-- -- Vérifier l'historique
-- SELECT * FROM games_history WHERE game_id = 123 ORDER BY changed_at DESC;
--
-- ⚠️ DIFFÉRENCES POSTGRESQL vs MariaDB:
-- 1. IS DISTINCT FROM au lieu de !=  (gère NULL correctement)
-- 2. Fonction séparée (RETURNS TRIGGER)
-- 3. TIMESTAMP au lieu de DATETIME
-- 4. SERIAL au lieu de AUTO_INCREMENT
--
-- 💡 IS DISTINCT FROM:
-- Opérateur PostgreSQL qui gère NULL correctement:
-- - NULL IS DISTINCT FROM NULL → FALSE
-- - NULL IS DISTINCT FROM 5 → TRUE
-- - 5 IS DISTINCT FROM 5 → FALSE
-- - 5 IS DISTINCT FROM 10 → TRUE
--
-- Équivalent à (mais plus simple):
-- (OLD.col != NEW.col) OR
-- (OLD.col IS NULL AND NEW.col IS NOT NULL) OR
-- (OLD.col IS NOT NULL AND NEW.col IS NULL)
--
-- 💡 CAS D'USAGE:
-- - Audit trail complet (qui a changé quoi et quand)
-- - Rollback manuel (restaurer une ancienne valeur)
-- - Analyse des tendances (évolution des scores dans le temps)
-- - Conformité (conserver historique des modifications)
-- ============================================

