-- ============================================
-- EXERCICE: Procédure simple (sans paramètres)
-- NIVEAU: 🔴 Avancé - Procédures Stockées
-- CONCEPTS: CREATE PROCEDURE, UPDATE, GET DIAGNOSTICS
--
-- 📚 Documentation PostgreSQL :
-- - [CREATE PROCEDURE](https://www.postgresql.org/docs/current/sql-createprocedure.html)
-- - [PL/pgSQL Procedures](https://www.postgresql.org/docs/current/plpgsql-structure.html)
-- - [GET DIAGNOSTICS](https://www.postgresql.org/docs/current/plpgsql-statements.html#PLPGSQL-STATEMENTS-DIAGNOSTICS)
--
-- 🎯 OBJECTIF PÉDAGOGIQUE:
-- Créer une procédure stockée basique qui effectue une opération
-- et retourne le nombre de lignes affectées.
--
-- 💡 QU'EST-CE QU'UNE PROCÉDURE STOCKÉE ?
-- Une procédure est un ensemble d'instructions SQL sauvegardées
-- dans la base de données, qu'on peut appeler avec CALL.
--
-- Avantages:
-- - Réutilisabilité du code
-- - Performance (compilée)
-- - Logique métier centralisée
-- - Sécurité (permissions granulaires)
--
-- ============================================
-- CONSIGNE:
-- Créez une procédure 'sp_cleanup_old_data' qui marque les jeux
-- trop anciens sans beaucoup de notes comme "non notés".
--
-- Nom: sp_cleanup_old_data
-- Paramètres: AUCUN
--
-- Action:
-- Mettre metacritic à NULL pour les jeux qui répondent à:
-- - year < 1990
-- - ratings_count < 10
--
-- Retour:
-- RAISE NOTICE pour afficher le nombre de lignes modifiées
-- (PostgreSQL n'a pas de SELECT direct dans les procédures,
--  on utilise RAISE NOTICE ou un paramètre OUT)
--
-- 💡 SYNTAXE POSTGRESQL (PL/pgSQL):
-- CREATE OR REPLACE PROCEDURE nom_procedure()
-- LANGUAGE plpgsql
-- AS $$
-- DECLARE
--     rows_affected INT;
-- BEGIN
--     -- Instructions SQL
--     UPDATE ...
--
--     -- Récupérer le nombre de lignes modifiées
--     GET DIAGNOSTICS rows_affected = ROW_COUNT;
--
--     -- Afficher le résultat
--     RAISE NOTICE 'Rows affected: %', rows_affected;
-- END;
-- $$;
--
-- 💡 UTILISATION:
-- CALL sp_cleanup_old_data();
--
-- ⚠️ DIFFÉRENCES POSTGRESQL vs MariaDB:
-- 1. Pas de DELIMITER // (utilise $$ à la place)
-- 2. LANGUAGE plpgsql obligatoire
-- 3. GET DIAGNOSTICS au lieu de ROW_COUNT()
-- 4. DECLARE avant BEGIN
-- 5. RAISE NOTICE au lieu de SELECT pour afficher
--
-- 💡 ALTERNATIVE avec OUT parameter:
-- CREATE OR REPLACE PROCEDURE sp_cleanup_old_data(OUT rows_affected INT)
-- LANGUAGE plpgsql
-- AS $$
-- BEGIN
--     UPDATE games
--     SET metacritic = NULL
--     WHERE year < 1990 AND ratings_count < 10;
--
--     GET DIAGNOSTICS rows_affected = ROW_COUNT;
-- END;
-- $$;
-- ============================================

