-- ============================================
-- EXERCICE: Vue avec GROUP_CONCAT (agrégation de texte)
-- NIVEAU: 🔴 Avancé - Vues
-- CONCEPTS: CREATE VIEW, GROUP_CONCAT, dénormalisation
--
-- 📚 Documentation MariaDB :
-- - [CREATE VIEW](https://mariadb.com/kb/en/create-view/)
-- - [GROUP_CONCAT](https://mariadb.com/kb/en/group_concat/)
--
-- 🎯 OBJECTIF PÉDAGOGIQUE:
-- Utiliser GROUP_CONCAT dans une vue pour créer des colonnes
-- avec des listes de valeurs (ex: "Action, RPG, Adventure").
--
-- 💡 GROUP_CONCAT:
-- Concatène les valeurs d'un groupe en une seule chaîne.
-- Très utile pour dénormaliser des relations many-to-many.
--
-- Syntaxe:
-- GROUP_CONCAT(DISTINCT colonne ORDER BY colonne SEPARATOR ', ')
--
-- ============================================
-- CONSIGNE:
-- Créez une vue 'view_high_quality_games' qui liste les jeux de haute qualité
-- avec leurs genres concaténés.
--
-- Colonnes de la vue:
-- - id (INT) : ID du jeu
-- - name (VARCHAR) : nom du jeu
-- - year (INT) : année de sortie
-- - metacritic (INT) : score Metacritic
-- - ratings_count (INT) : nombre de notes
-- - genres (TEXT) : genres séparés par des virgules (ex: "Action, RPG")
--
-- Jointures:
-- games -> game_genres -> genres
--
-- Filtres:
-- - metacritic >= 85 (haute qualité uniquement)
--
-- Agrégation:
-- - GROUP BY sur games.id (et les colonnes non-agrégées)
-- - GROUP_CONCAT(DISTINCT genres.name ORDER BY genres.name SEPARATOR ', ') AS genres
--
-- 💡 ATTENTION:
-- Quand on utilise GROUP_CONCAT, il faut GROUP BY sur toutes les colonnes
-- non-agrégées (id, name, year, metacritic, ratings_count).
--
-- 💡 UTILISATION:
-- SELECT * FROM view_high_quality_games WHERE year = 2020;
-- ============================================
